### ISSUE TITLE
No plugin found for prefix 'releaser'

### ISSUE THREAD

**Issue by darrin** [danielflower/multi-module-maven-release-plugin#1]
Guys - 

This looks great!! Thanks for putting it together!

I'm having what I hope is a simple issue and thus continues my love-hate relationship with maven...

```
mvn -cpu releaser:help -Ddetail=true -Dgoal=release

... lots of stuff ellided...

[ERROR] No plugin found for prefix 'releaser' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/Users/quantum/.m2/repository), central (http://repo.maven.apache.org/maven2)] -> [Help 1]

... more stuff ellided...

```

I added the '-cpu' to try and force maven to search repos for plugins/dependencies.  
It sure does LOOK like your stuff is out there... and I've been building for months with no trouble otherwise - no apparent changes other than your library and the rest of my project still builds properly.  

I added the repositories and pluginRepositories sections only after I got the failure... the errors didn't change.  Generally I find with Maven that I've done (or not done) something silly... Any thoughts?

Here's my pom for what it's worth:

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.xyz.abc</groupId>
    <artifactId>webend</artifactId>
    <packaging>pom</packaging>
    <version>1.1</version>
    <name>Web and backend services</name>

    <modules>
        <module>common</module>
        <module>web</module>
        <module>backend</module>
    </modules>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>com.github.danielflower.mavenplugins</groupId>
                    <artifactId>multi-module-maven-release-plugin</artifactId>
                    <version>1.0.1</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <configuration>
                        <source>1.7</source>
                        <target>1.7</target>
                    </configuration>
                </plugin>

            </plugins>
        </pluginManagement>
    </build>

    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>3.8.1</version>
            <scope>test</scope>
        </dependency>
    </dependencies>


    <repositories>
        <repository>
            <id>central</id>
            <name>Maven Repository Switchboard</name>
            <layout>default</layout>
            <url>http://repo1.maven.org/maven2</url>
        </repository>
    </repositories>

    <pluginRepositories>
        <pluginRepository>
            <id>central</id>
            <name>Maven Plugin Repository</name>
            <url>http://repo1.maven.org/maven2</url>
        </pluginRepository>
    </pluginRepositories>

</project>
```

Thanks much!

**Comment by danielflower** [comment]
Hi Darren, yes I think this should be simple....

You need to move the plugin declaration outside of the pluginManagement node. The `<plugins>` node should be a direct descendent of the `<build>` node. Give that a try and let me know how it goes.

Cheers.

**Comment by pmibal** [comment]
I am experiencing the exact same issue.  @darrin, did the solution work for you?

**Comment by danielflower** [comment]
I actually saw this on one project where everything appeared to be set up correctly. Maven was ignoring the prefix for some reason. Can you try `multi-module-maven-release-plugin:release` instead? Or maybe `com.github.danielflower.mavenplugins:multi-module-maven-release-plugin:release`

**Comment by darrin** [comment]
Sorry guys - I'm a victim of shifting priorities and got pulled off that project shortly after reporting the issue.

**Comment by frizzlebit** [comment]
I found that the missing prefix error is a generic maven issue related to how you declare the plugin. I found that I needed to declare the plugin within /build/pluginManagement/plugins of the multi-module pom.xml you use to start the build. You must also declare it in the same section of all the children modules.

My example:
```xml
	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>com.github.danielflower.mavenplugins</groupId>
					<artifactId>multi-module-maven-release-plugin</artifactId>
					<version>1.0.2</version>
				</plugin>			
			</plugins>
		</pluginManagement>
		<plugins>
			<!-- 
			| Get more detail with: mvn releaser:help -Ddetail=true -Dgoal=release 
			-->
			<plugin>
				<groupId>com.github.danielflower.mavenplugins</groupId>
				<artifactId>multi-module-maven-release-plugin</artifactId>
				<configuration>
					<releaseGoals>
						<releaseGoal>deploy</releaseGoal>
					</releaseGoals>
				</configuration>				
			</plugin>
		</plugins>
	</build>
```

This solution worked for me. For more complex scenarios consult:
https://maven.apache.org/guides/introduction/introduction-to-plugin-prefix-mapping.html

**Comment by danielflower** [comment]
I did a bit more digging around this. This will happen in a multi-module project where there is at least one module that does not have a parent in the same repo (or more specifically, when a module and its parent don't declare the release plugin).

I hope to spend some time to see if I can get around this. Until then, use the fully qualified name or declare the plugin in any module that doesn't inherit the plugin from an ancestor pom already.

**Comment by danielflower** [comment]
Closing as this is just a maven behaviour that can't be changed. Workaround: make sure every module has a reference to the plugin (either directly or via a parent), or call the goal with the full plugin name: `com.github.danielflower.mavenplugins:multi-module-maven-release-plugin:release`

**Comment by bbolli** [comment]
The solution that worked for me was to add this to my `.m2/settings.xml`:

    <pluginGroups>
      <pluginGroup>com.github.danielflower.mavenplugins</pluginGroup>
    </pluginGroups>
