### ISSUE TITLE
Add option to release with untracked files

### ISSUE THREAD

**Issue by kobynet** [danielflower/multi-module-maven-release-plugin#125]
When using containers/pods to build & release, we sometimes want to mount misc secrets like google service account etc as local file (this is recommended by gcp as well). in order to, for example, upload a file to a bucket (all part of the release).

In the current implementation, there is a limitation for that [repo.errorIfNotClean();](https://github.com/danielflower/multi-module-maven-release-plugin/blob/master/src/main/java/com/github/danielflower/mavenplugins/release/ReleaseMojo.java#L149).

I believe there should be a flag to skip this test in such scenarios.

**Comment by mtivi** [comment]
You can avoid that issue by adding those files to your `.gitignore`

**Comment by kobynet** [comment]
@mtivi That is correct if the owner of the maven project is the owner of the release job (let's assume jenkins job to release).
When that is not the case, we should be able to tell the plugin to ignore specific files at plugin runtime, because, as part of the job we add files like service accounts, etc.

How google credential works is that it expects an environment variable that points to a local file (the service account file).
This is a common practice also in other cloud providers, to add the service account file at build time (it can be any file name)

**Comment by danielflower** [comment]
Thanks, released in `3.6.1`
