### ISSUE TITLE
git - change was ignored and module was not released

### ISSUE THREAD

**Issue by Dhana-Krishnasamy** [danielflower/multi-module-maven-release-plugin#13]
Hi,
I had singe character changes in two lines of my protofile. The plugin ignored it and didnt release the version. Later when I reordered multiple lines, it did detect the change and released it.  Btw this is in version 1.2.0.

**Comment by danielflower** [comment]
Yes, this seems to be an outstanding problem where jgit isn't reporting changes. Haven't been able to reproduce yet unfortunately.

**Comment by danielflower** [comment]
It's possible this is fixed in 1.4.2 but I wasn't able to reproduce it in a test, so can't be sure.

**Comment by danielflower** [comment]
From my own experience, I think this is sorted now so am closing this.
