### ISSUE TITLE
[deploy] [3.6.1] Cannot release project with submodules with dependency

### ISSUE THREAD

**Issue by timonych** [danielflower/multi-module-maven-release-plugin#138]
Hello everyone!

We have a problem with one project which contains submodules.
Some of them looks to each other.
Pom.xml with dependency (placeholder **${project.version}**):
```
    <dependencies>
        <dependency>
            <groupId>groupId</groupId>
            <artifactId>artifactId</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>
```
When we are building release version via `mvn releaser:release` it looks then releaser doesn't build and install each artifact to local repository and fails.
```
[ERROR] Failed to execute goal on project api: Could not resolve dependencies for project groupId:artifactId:jar:1.0.12: The following artifacts could not be resolved: groupId:artifactId-0:jar:1.0.12, groupId:artifactId-1:jar:1.0.12, groupId:artifactId-2:jar:1.0.12, groupId:artifactId-3:jar:1.0.12: Could not find artifact groupId:artifactId-4:jar:1.0.12 in ARTIFACTORY (artifactory-link) -> [Help 1]
```
If we use `mvn deploy` after failure with `releaser:releaser` - project with submodules deployed without any error. But it's not good for automation.

Is there any workaround with `releaser:release` or it can be bug?

**Comment by kobynet** [comment]
I'm not sure what you are trying to do, working with a multi-module maven project with both aggregator/parent-child mode is relatively straightforward and should work(or else most integration tests would fail). 

Can you provide a simple repository/integration test where this can be reproduced?

**Comment by timonych** [comment]
@kobynet 
Thanks for Your feedback.

I have created a repo with similliar problem.
https://github.com/timonych/java-ws-wls-dev

```
[ERROR] Failed to execute goal on project ws-wls-ear-second: Could not resolve dependencies for project ru.pa.ws:ws-wls-ear-second:ear:1.0.0: ru.pa.ws:ws-wls-ear:jar:1.0.0 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project ws-wls-ear-second: Could not resolve dependencies for project ru.pa.ws:ws-wls-ear-second:ear:1.0.0: ru.pa.ws:ws-wls-ear:jar:1.0.0 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced
```
Module `ws-wls-ear-second` depend to `ws-wls-ear`.
When releaser is used it couldn't release `ws-wls-ear-second` because `ws-wls-ear` doesn't installed to local repo.

**Comment by kobynet** [comment]
@timonych I see you are using 
`<groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-release-plugin</artifactId>`

This is a different release plugin by apache.

**Comment by timonych** [comment]
@kobynet 

There are 2 plugins included in pom.xml
```
        <plugin>
            <groupId>com.github.danielflower.mavenplugins</groupId>
            <artifactId>multi-module-maven-release-plugin</artifactId>
            <version>3.6.1</version>
            <configuration>
                <skipTests>true</skipTests>
                <noChangesAction>ReleaseNone</noChangesAction>
            </configuration>
        </plugin>
```
and 
```
       <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-release-plugin</artifactId>
            <version>2.5.3</version>
            <configuration>
                <tagNameFormat>v@{project.version}</tagNameFormat>
                <autoVersionSubmodules>true</autoVersionSubmodules>
                <releaseProfiles>releases,weblogic</releaseProfiles>
                <preparationGoals>clean jxr:jxr install</preparationGoals>
                <goals>deploy</goals>
            </configuration>
            <dependencies>
                <dependency>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-scm-plugin</artifactId>
                    <version>1.8.1</version>
                </dependency>
            </dependencies>
        </plugin>
```

Is there any conflicts when mvn used with releaser by command `mvn releaser:release`.
I have thought that with argument `releaser:release` mvn is using `multi-module-maven-release-plugin`.

By the way, I have removed `maven-release-plugin` from `pom.xml` and nothing has changed.
I'm getting the same error.

**Comment by timonych** [comment]
The issue is not actual now.

The problem was with `dependency version` and `dependency type`.
