### ISSUE TITLE
Version properties and maven-assembly-plugin

### ISSUE THREAD

**Issue by gwenn** [danielflower/multi-module-maven-release-plugin#143]
Version properties are not properly resolved by other plugins.
For example, in one POM:
```xml
<project>
    <!-- ... -->
    <properties>
        <onedep.version>1.1-SNAPSHOT</onedep.version>
    </properties>
    <!-- ... -->
    <dependencies>
        <dependency>
            <groupId>com.github</groupId>
            <artifactId>onedep</artifactId>
            <version>${onedep.version}</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <executions>
                    <execution>
                        <id>zip</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <descriptors>
                                <descriptor>assembly.xml</descriptor>
                            </descriptors>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
```
and assembly descriptor:
```xml
<assembly>
    <id>zip</id>
    <includeBaseDirectory>false</includeBaseDirectory>
    <formats>
        <format>zip</format>
    </formats>
    <files>
        <file>
            <source>deps.xml</source>
            <filtered>true</filtered>
        </file>
    </files>
</assembly>
```
and filtered file:
```xml
<deps>
    <dep>
        <name>onedep</name>
        <version>${onedep.version}</version>
    </dep>
</deps>
```
In generated assembly, we have `<version>1.1-SNAPSHOT</version>` instead of the actual version resolved by `multi-module-maven-release-plugin`

**Comment by kobynet** [comment]
I see you already figured out about "versionReport". I had similar issues and that is why I contributed that part. 
I guess you can close this issue.

**Comment by gwenn** [comment]
Would you mind explaining why only dependencies are correctly resolved by this plugin and not properties ?
Thanks.

**Comment by kobynet** [comment]
You are using assembly descriptor which is part of maven-assembly-plugin, this is just a different plugin, with its own logic.

multi-module-maven-release-plugin is not aware of what is <assembly> element etc.

**Comment by gwenn** [comment]
But maven-assembly-plugin correctly resolves dependencies, so why not also properties ?

**Comment by kobynet** [comment]
multi-module-maven-release-plugin works differently, it finds out what is the next version and rewrites the pom with this new version, it goes through all dependencies and plugins declaration, and replaces the version itself, but the property stays the same, that is 1.1-SNAPSHOT.

I guess it's possible to add an option to override the property, if one is used, with the new version as well.
Most of it happens in [PomUpdater](https://github.com/danielflower/multi-module-maven-release-plugin/blob/master/src/main/java/com/github/danielflower/mavenplugins/release/PomUpdater.java )

I believe a PR is welcome if you are willing to contribute.

**Comment by gwenn** [comment]
Thanks for the explanations.
