### ISSUE TITLE
[ERROR] fatal: Could not switch to '/opt/git-2.7.4/etc/': No such file or directory

### ISSUE THREAD

**Issue by patrickhancke** [danielflower/multi-module-maven-release-plugin#44]
I'm using the 2.0.8 version of the plugin. Release build runs on a Bamboo agent. The error I get:

`[ERROR] fatal: Could not switch to '/opt/git-2.7.4/etc/': No such file or directory`

 Full log in attachment.
[plan-272991023-JOB1-3.txt](https://github.com/danielflower/multi-module-maven-release-plugin/files/626859/plan-272991023-JOB1-3.txt)

If I understand well, the plugin doesn't need the native git client to be installed on the agent. So I'm wondering why it tries to find the find the configuration in the directory mentioned above.

**Comment by danielflower** [comment]
Hi, yes you are right that it doesn't use the native git client. I don't know why that error would occur or what it means, but interestingly it looks like the plugin actually worked and ran the release?

**Comment by patrickhancke** [comment]
Hi Daniel,

The problem is that the plugin actually deploys the versioned artefact to Nexus but it doesn't tag the repository.

I've enabled Maven's -X option to have more logging: 
[plan-272991023-JOB1-5.zip](https://github.com/danielflower/multi-module-maven-release-plugin/files/630554/plan-272991023-JOB1-5.zip)

Maybe this can help you investigating the problem.

**Comment by danielflower** [comment]
Thanks. Looks like the log line is caused by https://bugs.eclipse.org/bugs/show_bug.cgi?id=476639 (in jgit - the java git library this plugin uses).

I'm going to create a new release version with an updated jgit that you can try. It should remove the error you see, but whether or not it fixes the actual problem is uncertain. 

I'll post the new version of the plugin here when it's ready.

**Comment by danielflower** [comment]
Please try with version `2.0.9`

**Comment by patrickhancke** [comment]
I tried with version 2.0.9 and the error disappears but I still don't have tags in my repository.

[debug-output-2.0.9.txt](https://github.com/danielflower/multi-module-maven-release-plugin/files/635923/debug-output-2.0.9.txt)
