### ISSUE TITLE
Deploy should inherit settings from releaser

### ISSUE THREAD

**Issue by attleysmith** [danielflower/multi-module-maven-release-plugin#45]
Jenkins Config File Provider Plugin passes selected maven settings to the release mojo from a temporary created settings file (e.g. -s /tmp/settings4492055473509834167.xml). These settings are set on release but not passed to releaser's goals.

**Comment by danielflower** [comment]
Hi, I tried to reproduce this problem in a test: https://github.com/danielflower/multi-module-maven-release-plugin/commit/85fe1922f825ded2dab22629f038524470a56641

I added a test where it starts the plugin by using `-s test-projects/sample-global-settings.xml` which enables a profile. The test proves that the settings file can be set this way. The test passed with your changes.

I then reverted your change, and the test still passed. So it seems that the default behaviour is to inherit the settings. Can you show an example of where this doesn't happen? Or better yet reproduce the problem in the test linked to above?

**Comment by danielflower** [comment]
Ignore me. My test was bad. Your pull request is good and fixes it.

**Comment by danielflower** [comment]
Fixed in `2.1.0`
