### ISSUE TITLE
Release messes up pom files

### ISSUE THREAD

**Issue by douglassparker** [danielflower/multi-module-maven-release-plugin#51]
Great plugin. However, the release task removes comments in the pom file. It also does not preserve the formatting. This is irritating and, it would seem, unnecessary when only version numbers need to be replaced.

**Comment by Infrag** [comment]
In my case it also broke build because of some parametters which were made invalid by reformatting.

**Comment by danielflower** [comment]
Just to be clear, and correct me if I'm wrong, but this pom is only changed for the duration of a release, and then the formatting changes are reverted after a release.

Note the plugin just uses Maven's own classes to write the pom, so if it's breaking stuff then perhaps the pom is too fragile. I don't intend to change this behaviour as I think trying to do this with custom code will introduce bugs.

**Comment by douglassparker** [comment]
The format changes are permanent. The order of tags is not preserved. Most annoying of all - comments are permanently deleted, which destroys your ability to document your pom.  The formatting changes are not reverted once the release is complete. The changes don't "break stuff", the pom still works. 

I understand your reluctance to deviate from the use of Maven classes, but this is annoying - particularly the deletion of comments.

On balance, though, I love this plugin. Great work!

On Apr 16, 2017, at 04:20 AM, Daniel Flower <notifications@github.com> wrote:

Just to be clear, and correct me if I'm wrong, but this pom is only changed for the duration of a release, and then the formatting changes are reverted after a release.
Note the plugin just uses Maven's own classes to write the pom, so if it's breaking stuff then perhaps the pom is too fragile. I don't intend to change this behaviour as I think trying to do this with custom code will introduce bugs.

**Comment by danielflower** [comment]
Sounds like something is going wrong for you then as it is supposed to retain comments. In fact I just added a test to ensure that happens: https://github.com/danielflower/multi-module-maven-release-plugin/commit/ada7775514ad81e0145ebb2313ea753c6aae45af

The following is the code that reverts the pom:

    try {
        String pathRelativeToWorkingTree = Repository.stripWorkDir(workTree, changedFile);
        git.checkout().addPath(pathRelativeToWorkingTree).call();
    } catch (Exception e) {
        hasErrors = true;
        log.error("Unable to revert changes to " + changedFile + " - you may need to manually revert this file. Error was: " + e.getMessage());
    }

Do you see that "Unable to revert" error message?

**Comment by douglassparker** [comment]
I did not notice it. I'll run a test and get back to you.

**Comment by douglassparker** [comment]
Sorry to take so long to follow up. I have not done a release in a while. In my latest release, the pom files were not corrupted and the comments were not deleted. I suspect that this was previously caused by the aborted release that prompted me to open issue 50 (duplicate artifact ids cause a release to fail).  So it seems that this may be an issue if the release aborts, but not if it is successful.

Kudos for a great plugin.
