### ISSUE TITLE
Support for modules in separate repositories

### ISSUE THREAD

**Issue by Infrag** [danielflower/multi-module-maven-release-plugin#53]
When Maven modules are in separate repositories release plugin does not work.

**Comment by danielflower** [comment]
This is by design as the whole plugin is built on the premise that the modules are in a single repo. I think supporting multiple repos would have to be done in a fork.

**Comment by Infrag** [comment]
I've forked your project. I've got to state when mulitrepo multimodule release seems to work. I think that it should be also usable for singlerepo multimodule projects. So it could be probably merged together. It needs some cleaning and polishing

**Comment by Infrag** [comment]
https://github.com/Infrag/multi-module-maven-release-plugin/tree/multirepo-project
