### ISSUE TITLE
https authentication

### ISSUE THREAD

**Issue by pauldavidgilligan** [danielflower/multi-module-maven-release-plugin#59]
Any thoughts on if or how we can add https authentication?

**Comment by danielflower** [comment]
I have thoughts, but no time to work on it.

From a user point of view, you'd want the username/password to be stored in the user's settings.xml, and referenced from the project's pom.xml by a name - much like how uploading to Nexus can be handled.

From an implementation point of view, this project uses [jgit](https://eclipse.org/jgit/) which handles HTTP authentication - wouldn't be that difficult to get it working I think.

**Comment by pauldavidgilligan** [comment]
yes using maven master password which is what I am doing now.

**Comment by silmarx** [comment]
I'm trying to use this plugin but I get an authentication error from JGit saying "authentication is required but CredentialProvider was registered".
I'm using a server with https.
I suppose this is the same issue, right?

**Comment by danielflower** [comment]
Yes, assuming you need a password to upload.

**Comment by silmarx** [comment]
What do you mean by "upload". I'm talking about JGit so I suppose you "push", is it?
I'm asking just to make sure that this refers to the HTTPS authentication on Git server and not to the NEXUS authentication. If this is the case I cannot use this plugin as my Git server requires HTTPS authentication.

**Comment by danielflower** [comment]
HTTPS authentication was added in version 3.0.2

Please see https://danielflower.github.io/multi-module-maven-release-plugin/https-authentication.html
