### ISSUE TITLE
Allow versions x.y.z-buildnumber

### ISSUE THREAD

**Issue by marcel-steinbach-mpf** [danielflower/multi-module-maven-release-plugin#60]
Our business versions have 3 parts, e.g. `1.2.3`. We append the build numbers as 4th digit, but for maven to be able to order the releases, this has to be separated with a dash ([How Version Numbers Work in Maven]
(https://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm#A1000661))

The plugin should apply the versioning schema of maven correctly, e.g. when there is a business version `1.2.3`, the plugin should use `1.2.3-0` as verision, not `1.2.3.0`

**Comment by danielflower** [comment]
Thanks for the pull request. Released in `2.1.4`
