### ISSUE TITLE
Any way to execute a plugin from a releaseProfile before create the tags?

### ISSUE THREAD

**Issue by cvgaviao** [danielflower/multi-module-maven-release-plugin#71]
Hello,
I've created  a profile with the enforcer plugin in order to ensure that some properties are being called before the release begin.
I've added that profile to the `releaseProfile` property and it is being activated, BUT ONLY after the release plugin have created the TAGs.
If the properties was not provided I have to remove the tags by hand... 

>             <plugin>
>                <groupId>com.github.danielflower.mavenplugins</groupId>
>                <artifactId>multi-module-maven-release-plugin</artifactId>
>                <version>3.0.0</version>
>                <configuration>
>                    <releaseProfiles>
>                        <releaseProfile>when-releasing-ensure-requirements</releaseProfile>
>                    </releaseProfiles>
>                </configuration>
>            </plugin>

>         <profile>
>           
>           
>            <id>when-releasing-ensure-requirements</id>
>            <activation>
>                <activeByDefault>false</activeByDefault>
>            </activation>
>            <build>
>                <plugins>
>                    <plugin>
>                        <groupId>org.apache.maven.plugins</groupId>
>                        <artifactId>maven-enforcer-plugin</artifactId>
>                        <inherited>true</inherited>
>                        <configuration>
>                            <failFast>true</failFast>
>                            <fail>true</fail>
>                            <ignoreCache>true</ignoreCache>
>                        </configuration>
>                        <executions>
>                            <execution>
>                                <id>enforce-property</id>
>                                <goals>
>                                    <goal>enforce</goal>
>                                </goals>
>                                <phase>validate</phase>
>                                <configuration>
>                                    <rules>
>                                        <requireProperty>
>                                           <property>c8tech.build.release</property>
>                                            <message>You must set the
>                                                release property, so all
>                                               profiles related are
>                                                called.
>                                            </message>
>                                        </requireProperty>
>                                    </rules>
>                                </configuration>
>                            </execution>
>                        </executions>
>                    </plugin>
>                </plugins>
>            </build>
>        </profile>

**Comment by danielflower** [comment]
You can now specify `<arguments>-Dlike=this</arguments>` in the releaser config, as of version `3.0.1`.

As for the other query, this plugin will always tag first before running anything. This is because when things go it is difficult to roll back, e.g. if you have uploaded a version to nexus and then the release fails, it can't be deleted, so you must increment the build number. The release plugin cannot know what is happening so it prefers to have excess tags rather than the occasional unbuildable build.
