### ISSUE TITLE
Please support git comment prefix

### ISSUE THREAD

**Issue by rverma-nikiai** [danielflower/multi-module-maven-release-plugin#72]
A git comment prefix will allow the build tools to ignore a particular commit created by release plugin. Else this will endlessly create versions as each release on master will commit and cycle back to release process.

To skip this only thing required is git commit prefix. http://maven.apache.org/maven-release/maven-release-plugin/prepare-mojo.html#scmCommentPrefix

**Comment by danielflower** [comment]
Hello... unlike the official plugin, this release plugin does not create commits, it only tags it, therefore there are not commits to have any messages at all.
