### ISSUE TITLE
AWS CodeCommit support?

### ISSUE THREAD

**Issue by jnimis** [danielflower/multi-module-maven-release-plugin#73]
This is an awesome project!

I use SSH authentication for connecting to an AWS CodeCommit repo.  This involves referring to "codecommit credential-helper" in my ~/.gitconfig file. I'm not sure exactly what happens in the background...

It seems like your plugin can only get its credentials through the maven settings file, so I think I'm locked out for now. Any idea how hard this would be to solve?  Thanks!

John

**Comment by danielflower** [comment]
I don't know anything about AWS CodeCommit sorry. But all the git stuff is being handled by https://github.com/eclipse/jgit so if that supports it then it's probably possible. If not, then maybe not.

**Comment by jnimis** [comment]
Thanks - this hint was enough for me to get it working: for future reference, the trick is setting up https credentials for the IAM User (under "Security Credentials" in the AWS IAM console), and then following the plugin guide for https credentials in maven settings.
