### ISSUE TITLE
Managing a BOM?

### ISSUE THREAD

**Issue by stromnet** [danielflower/multi-module-maven-release-plugin#8]
Hi,

I got a project with common libraries, each library within a submodule. They are different enough to warrant individual releases, thus this plugin seems perfect.
I would like to have a BOM file with the "latest" version of all libraries, which the end-user projects can import via dependency management. It seems messy to update this manually for every release though.

Basically, I wan't end-user projects within the organization to automatically benefit from any minor patches the libraries get, without having to go through every project and bump the version number whenever a lib version changes.

Something like <version>[1.0.0,2.0.0)</version> and strict semantic versions could be an alternative approach.

Have you had any similar situations, and how do you solve them?

**Comment by stromnet** [comment]
After working with this for a day, I think "open" versions is probably not what I want, because I'd like stable releases.

But how about other projects (i.e. appX) depending on my libs (say libY, having version 1.2-SNAPSHOT)? During lib release, it would create 1.2.0
For "stable" code I just point appX  to depend on libY 1.2.0, and all is good.

During development though, I'd want to use 1.2-SNAPSHOT since I'm doing work on both library and app. I would like to avoid having to change appX pom from 1.2.0 to 1.2-SNAPSHOT back and forth.
And I would also forget to change back to 1.2.1 after I released libY 1.2.1.. Or does the plugin manage this automatically somehow?

Any hints on how you use this in your environment would be refreshing, now I'm quite stuck.. :)

**Comment by danielflower** [comment]
So `appX` and `libY` are in different git repos? Or at least not in the same Maven reactor as each other?

I'm not sure there is a clean way to handle this if you also want `appx` to use a snapshot version of `libY` sometimes. You just have to manually switch between them. If they are completely separate projects though would you really have a snapshot dependency that often? Well, the probably makes sense in many cases, but the plugin wasn't really designed to handle that. I'm not sure what to do about that.

Of course if `appX` and `libY` are part of the same maven reactor in the same git repo then you just always point at the current snapshot of `libY` and it will just work but I presume this is not what you meant.

The above two cases are how I use this plugin normally.

**Comment by stromnet** [comment]
Precisely, `appX` is in a standalone repo, so there is no way for maven in `appX` to know latest version of  `libY`, besides possibly looking in an actual repository.

Would something like this make sense? When building `appX`, which has a dep on `libY 1.2-SNAPSHOT`, the plugin would look in the configured (Maven) repos for latest 1.2.x of `libY` and use that as the dependency. This way a release of `appX` would never have a snapshot dep. However, there is always a chance that `libX 1.2.X` was older than `1.2-SNAPSHOT` because I forgot to release `libX` first.. So not really solid..

**Comment by stromnet** [comment]
I've ended up throwing out the BOM's, and use static versions when referencing a lib in `libY` from  `appX`. Seems most stable and makes most sense.

May look at using the versions-maven-plugin (http://www.mojohaus.org/versions-maven-plugin/) to bump dependency versions. 


As this was not really an issue with the software but more of a call for guidance, I'm closing.

**Comment by danielflower** [comment]
Thanks for the update.
