### ISSUE TITLE
Speed up integration tests

### ISSUE THREAD

**Issue by marcelstoer** [danielflower/multi-module-maven-release-plugin#91]
Each integration test (i.e. those in the `e2e` directory) contains this duplicated piece of code:

```java
@BeforeClass
public static void installPluginToLocalRepo() throws MavenInvocationException {
  MvnRunner.installReleasePluginToLocalRepo();
}
```

The plugin that is installed into the local Maven repo is always the same, though. This is needless duplication and costs time.

Proposed solution:
- create an integration test super class
- place that code in a `static {}` block there

**Comment by danielflower** [comment]
I agree that should definitely only be installed once. Anything to speed up the tests would be great.

I'm not keen on inheritance though. The `MvnRunner.installReleasePluginToLocalRepo()` could just detect if it has already been installed or not (e.g. by having a static boolean). The method could then be renamed to `ensureReleasePluginInstalledToLocalRepo()`

**Comment by marcelstoer** [comment]
> I'm not keen on inheritance though.

True, neither am I. I guess it comes down to choosing the lesser evil. Even if we can speed up test execution you still need to copy-paste those four lines of code. I feel there is probably a better third option but I haven't given it much thought yet.

**Comment by danielflower** [comment]
I just checked and actually it only installs the plugin once per test run already.
