### ISSUE TITLE
Local Plugin dependency not resolved when using -Snapshot

### ISSUE THREAD

**Issue by kobynet** [danielflower/multi-module-maven-release-plugin#96]
I have an issue where i have two modules under aggregated(parent) pom.
Module A is of type 'maven-plugin'.
Module B is of type jar.
Plugin A version is resolved through pluginManagement in aggregated(parent) pom.
Now when using parent version for example 1.0-SNAPSHOT, both modules get the right version which is 1.0.0 (first release) but release fails due to module B having snapshot dependency on Module A.

The source of the problem is in 
https://github.com/danielflower/multi-module-maven-release-plugin/blob/master/src/main/java/com/github/danielflower/mavenplugins/release/PomUpdater.java#L105

My solution is to check where the plugin is a ReleasableModule in the current release (and therefore it has real version and not snapshot).
I would be happy to make a PR, wanted to make sure this makes sense or am i missing something here?

**Comment by danielflower** [comment]
Hello, yes I think that sounds reasonable.

**Comment by danielflower** [comment]
Thanks for the pull request. Released in `3.2.3`
